#!/usr/bin/env ruby

# Handles all file system actions.
require 'pathname'
# Ruby multi threading.
require 'thread'
# Nice way to print out objects. Used for debug.
require 'pp'

test_dir = Pathname.new('tests')
results_dir = Pathname.new('results')

# OPERATOR OVERLOAD. I got tired of typing .read everywhere.
class Pathname
  def ===(t2)
    read == t2.read
  end
end

# Holds all information and extensions for a specific test.
class Test
  attr_reader :name
  attr_accessor :err_incorrect, :out_incorrect, :pixels_incorrect
  attr_accessor :passed_test, :failed_test, :previously_passed_test
  attr_accessor :correct_stdout, :correct_stderr, :correct_pixels

  def initialize(test_name)
    @name = test_name
    @err_incorrect = @out_incorrect = @pixels_incorrect = ''
    @passed_test = @failed_test = @previously_passed_test = 0
    @correct_stdout = @correct_stderr = @correct_pixels = false
    @result_files = %w(passed myout myerr mypixels)
    @test_files = %w(err out keypresses pixels jpg gpl pixels_option1 pixels_option2)
  end

  def display
    print @passed_test == 1 ? 'Passed ' : 'Failed '
    print "#{@name} "
    print "#{@out_incorrect} "
    print "#{@err_incorrect} "
    puts @pixels_incorrect
  end

  # Returns a Pathname object for the given extension.
  # i.e. Test<"t001">.gpl returns Pathname<"tests/t001.gpl">
  def method_missing(ext)
    temp_ext = ext.to_s.dup
    ext = ext.to_s.delete('?')
    if @test_files.include? ext
      test = Pathname.new("tests/#{@name}.#{ext}")
      return test.exist? if temp_ext[temp_ext.length - 1] == '?'
      return test
    elsif @result_files.include? ext
      test = Pathname.new("results/#{@name}.#{ext}")
      return test.exist? if temp_ext[temp_ext.length - 1] == '?'
      return test
    else
      fail("Unknown extension given #{p ext}")
    end
  end
end

# Convert numbers to t### format.
def format_test_number(tn)
  tn = tn.to_s
  tn.insert(0, '0') while tn.length < 3
  tn.insert(0, 't') unless tn =~ /t\d+{3}/
  abort("Test number can't be formatted.") unless tn =~ /t\d+{3}/
  Test.new(tn)
end

# Convert #-# test range to array of tests matching t### format.
def format_test_range(range)
  abort('Invalid test range.') unless /\d+-\d+/ =~ range
  # Parse left side of dash
  begin_range = range.match(/\d+/).to_s.to_i
  # Parse right side of dash
  end_range = range.match(/\d+$/).to_s.to_i
  tests = (begin_range..end_range).to_a.map { |t| format_test_number(t) }
  tests
end

# Does the gpl executable exist in current directory?
unless File.file? 'gpl'
  abort 'There is no gpl executable in this directory. gt is giving up.'
end

# Is the tests a directory and exist?
unless test_dir.directory?
  abort 'There is not a test subdirectory in this directory. gt is giving up.'
end

# Create results directory if it doesn't exist already.
results_dir.mkdir unless results_dir.directory?

# Determine what argument was given and format input.
queued_tests = if ARGV.last =~ /^(t)?\d+$/ # Single test number given
                 [format_test_number(ARGV.last.dup)]
               # Range of test numbers given
               elsif ARGV.last =~ /(t)?\d+-(t)?\d+/
                 format_test_range ARGV.last.dup
               # Run all tests
               else
                 # Get 3 digit number of last test in tests directory.
                 end_range = test_dir.entries
                                     .last
                                     .basename
                                     .to_s
                                     .sub('t', '')
                                     .gsub(/\..*/, '')
                 format_test_range "1-#{end_range}"
               end

# Remove tests that don't exist.
queued_tests.keep_if { |t| t.gpl.exist? }

# Make sure tests were found for given test number(s).
abort "<#{ARGV.last}> does not exist. Giving up." if queued_tests.empty?

# Remove tests that have a .passed file, Unless gtr is running as default.
unless ARGV.last.nil?
  queued_tests.each do |t|
    t.passed.unlink if t.passed?
  end
end

# Handle all the testing.
# t - Test object
def run_test(t)
  # Skip if test has been passed previously.
  if t.passed?
    t.previously_passed_test = 1
    return
  end

  # Keep track of CLI flags.
  gpl_flags = []
  # Set default seed.
  gpl_flags << '-s 42'

  if t.jpg?
    t.jpg.write 'no pixel file created'
    gpl_flags << "-dump_pixels #{t.mypixels.to_s}"
  end

  if t.keypresses?
    gpl_flags << '-stdin'
    `./gpl #{gpl_flags.join(' ')} #{t.gpl} < #{t.keypresses} > #{t.myout.to_s} 2> #{t.myerr.to_s}`
  else
    `./gpl #{gpl_flags.join(' ')} #{t.gpl} > #{t.myout.to_s} 2> #{t.myerr.to_s}`
  end

  t.correct_stdout = t.myout === t.out
  t.correct_stderr = t.myerr === t.err

  if t.jpg?
    t.correct_pixels = if t.mypixels === t.pixels
                         true
                       elsif t.pixels_option1? && t.mypixels === t.pixels_option1
                         true
                       elsif t.pixels_option2? && t.mypixels === t.pixels_option2
                         true
                       else
                         false
                       end
  else
    # No .jpg test exists so default to correct.
    t.correct_pixels = true
  end

  if t.correct_stdout && t.correct_stderr && t.correct_pixels
    t.passed_test = 1
    `touch #{t.passed.to_s}`
  else
    t.out_incorrect = '<stdout incorrect>' unless t.correct_stdout
    t.err_incorrect = '<stderr incorrect>' unless t.correct_stderr
    t.pixels_incorrect = '<pixels incorrect>' unless t.correct_pixels
    t.failed_test = 1
  end
end

threads = []
# Allow Threads to pop from queued_test without removing anything.
qt_dup = queued_tests.dup
# Allocate Tests to threads.
queued_tests.size.times { threads << Thread.new { run_test(qt_dup.pop) } }
# Wait for all threads to finish.
threads.each(&:join)

# Get stats of tests.
tr = {}
%w(passed_test failed_test previously_passed_test).each do |s|
  # Call Test.s for every Test and sum up values.
  tr[s] = queued_tests.map { |t| t.send(s) }.inject(:+)
end

# Print out each test result
queued_tests.each do |t|
  t.display if t.previously_passed_test == 0
end

total = tr['passed_test'].to_i + tr['failed_test'].to_i
puts "Passed #{tr['passed_test']} out of #{total} tests."
puts "Failed #{tr['failed_test']} out of #{total} tests."

if tr['previously_passed'].to_i > 0
  puts "  #{tr['previously_passed_test']} tests were skipped (passed on previous run)"
  puts '    "$ gt -all" to run all tests (recommended before you turn in assignment)'
  puts '    "$ gt 42" to run test t042.gpl'
end
