#!/usr/bin/env ruby

# Executes 515 tests in a given range.
# rt 1-10

# Parse left side of dash
begin_range = ARGV.last.dup.match(/\d+/).to_s.to_i
# Parse right side of dash
end_range = ARGV.last.dup.match(/\d+$/).to_s.to_i
# Define the whole range
range = (begin_range..end_range).to_a
# Run 515 tester for each test number in range.
# Split removes the Passed/Failed test count.
range.each { |i| puts `gt #{i}`.split("\n").first }
